name: template
description: An application that provide a code repository for flutter application

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Android : Version Name               + Version Code
# iOS     : CFBundleShortVersionString + CFBundleVersion
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

# flutter pub upgrade --major-versions
dependencies:
  flutter:
    sdk: flutter


  # Provide Cupertino Icon
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Provide a set of recommended lints to encourage good coding practices.
  flutter_lints: ^2.0.0

  # Provide a script to update all of the platform logo
  flutter_launcher_icons: ^0.9.2

  # Provide a script to update all of the platform splash screen
  flutter_native_splash: ^2.2.1

# Terminal Run: flutter pub run flutter_launcher_icons:main
flutter_icons:
  ios: true
  android: true
  image_path: asset/media/image/app_logo.png
  remove_alpha_ios: true
#  adaptive_icon_foreground: asset/image/icon/app.png
#  adaptive_icon_background: '#3C8DBC'

# Terminal Run: flutter pub run flutter_native_splash:create
flutter_native_splash:
  image: asset/media/image/app_splash.png
  color: '#FFFFFF'

# The following section is specific to Flutter packages.
flutter:

  # Provide Material Icon
  uses-material-design: true
